# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.hostname = "ubuntu20"
    config.vm.provider "virtualbox" do |v|
        v.name = "ubuntu20"
        v.memory = 4096
        v.cpus = 2
        v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
    end
    config.vm.provision "shell", inline: <<-SHELL
    apt-get update -y
    apt-get install -y curl
    curl -LO https://raw.githubusercontent.com/perlogix/opsy/main/linux-ops/install.sh
    chmod 0755 ./install.sh
    ./install.sh
SHELL
end